{% set name = "opentelemetry-instrumentation-sklearn" %}
{% set version = "0.33b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-sklearn-{{ version }}.tar.gz
  sha256: d1b23aa9625043817c22e44535acfe4b95d214bdb24fe977fd37fadd4d4276ab

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.33b0
    - python >=3.6
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test ==0.24b0
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test ==0.25b0
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test ==0.25b1
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test ==0.25b2
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test-utils ==0.26b1
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test-utils ==0.27b0
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test-utils ==0.28b0
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test-utils ==0.28b1
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test-utils ==0.29b0
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test-utils ==0.30b0
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test-utils ==0.30b1
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test-utils ==0.31b0
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test-utils ==0.32b0
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test-utils ==0.33b0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-sklearn
  summary: OpenTelemetry sklearn instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
