{% set name = "opentelemetry-instrumentation-sklearn" %}
{% set version = "0.25b2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-sklearn-{{ version }}.tar.gz
  sha256: d01428ff4d6c66f39d508d19dc5ce7e252e485dca79433bc874509d22b84f8a7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.25b2
    - python >=3.6
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test ==0.24b0
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test ==0.25b0
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test ==0.25b1
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test ==0.25b2

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-sklearn
  summary: OpenTelemetry sklearn instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
