{% set name = "opentelemetry-instrumentation-sklearn" %}
{% set version = "0.26b1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-sklearn-{{ version }}.tar.gz
  sha256: 46e5278e35afe7fd060014a0e8e9f3fe5e7c8a8e2009ed95165113ba32272d6c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.26b1
    - python >=3.6
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test ==0.24b0
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test ==0.25b0
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test ==0.25b1
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test ==0.25b2
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test-utils ==0.26b1

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-sklearn
  summary: OpenTelemetry sklearn instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
